(function initialiseTalentRadarData() {
  "use strict";

  const snapshotDate = "2026-05";
  const inboxProvenance =
    "Confirmed from the user's inbox in the supplied project notes; current availability is unverified.";
  const aggregateProvenance =
    "Confirmed as a saved-search alert in the user's inbox in the supplied project notes; the underlying vacancies were not individually resolved.";

  const sapGroups = [
    {
      id: "functional",
      name: "Functional",
      category: "Functional",
      modules: [
        "FI/CO",
        "SD",
        "MM",
        "PP",
        "QM",
        "PM",
        "WM/EWM",
        "TM",
        "HCM/SuccessFactors",
        "Ariba",
        "IBP",
        "GRC",
        "CRM/CX"
      ]
    },
    {
      id: "technical",
      name: "Technical",
      category: "Technical",
      modules: [
        "ABAP/OO-ABAP",
        "BTP",
        "Fiori/UI5",
        "CDS/OData",
        "Integration Suite (CPI/PI-PO)",
        "BW/4HANA",
        "SAC",
        "Basis",
        "Security"
      ]
    },
    {
      id: "leadership",
      name: "Leadership",
      category: "Leadership",
      modules: [
        "Solution Architect",
        "Enterprise Architect",
        "S/4HANA Program Manager",
        "Delivery Lead"
      ]
    }
  ];

  const otherGroups = [
    {
      id: "other-provisional",
      name: "Other workstream",
      category: "Other",
      isProvisional: true,
      modules: ["General PM/BA", "Data / Cloud", "Other ERP"]
    }
  ];

  const modules = [
    ...sapGroups.flatMap((group) =>
      group.modules.map((name) => ({
        id: name
          .toLowerCase()
          .replaceAll("&", "and")
          .replaceAll("/", "-")
          .replaceAll(" ", "-")
          .replaceAll("(", "")
          .replaceAll(")", ""),
        name,
        stream: "SAP",
        group: group.name,
        aliases:
          name === "FI/CO"
            ? ["FICO", "FI", "CO"]
            : name === "ABAP/OO-ABAP"
              ? ["ABAP", "OO-ABAP"]
              : name === "Fiori/UI5"
                ? ["FIORI", "UI5"]
                : name === "Basis"
                  ? ["BASIS"]
                  : []
      }))
    ),
    ...otherGroups.flatMap((group) =>
      group.modules.map((name) => ({
        id: name.toLowerCase().replaceAll("/", "-").replaceAll(" ", "-"),
        name,
        stream: "Other",
        group: group.name,
        aliases: name === "Other ERP" ? ["NetSuite", "Oracle", "Workday", "Microsoft Dynamics"] : [],
        isProvisional: true
      }))
    )
  ];

  const jobs = [
    {
      id: "job-2026-05-seek-enterprise-architect",
      title: "SAP Enterprise Architect — S/4HANA, Signavio, LeanIX",
      company: "Private Advertiser",
      location: "Sydney NSW",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Leadership",
      module: "Enterprise Architect",
      rate: "$1,300–1,600/day",
      engagement: "Not stated",
      source: "SEEK",
      provenance: inboxProvenance,
      firstSeen: "2026-05",
      snapshotDate,
      priority: "priority",
      priorityReason:
        "Provisional priority signal: this is a May 2026 inbox record and the only supplied role with a stated day rate ($1,300–1,600/day).",
      summary:
        "Inbox-confirmed listing for an SAP Enterprise Architect covering S/4HANA, Signavio and LeanIX.",
      skills: ["Enterprise Architecture", "S/4HANA", "Signavio", "LeanIX"],
      isConfirmed: true,
      type: "Not stated",
      date: "2026-05",
      historicalState: "Historical May 2026 inbox snapshot; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The inbox role record is confirmed; its current live status is not."
    },
    {
      id: "job-2026-05-seek-senior-s4-consultants",
      title: "Multiple Senior SAP S/4HANA Consultants",
      company: "That Blue Screen",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Cross-functional",
      module: "Unclassified SAP",
      rate: null,
      engagement: "Not stated",
      source: "SEEK",
      provenance: inboxProvenance,
      firstSeen: "2026-05",
      snapshotDate,
      priority: "watch",
      priorityReason:
        "May 2026 inbox record with multiple senior positions mentioned; rate, modules and current availability were not supplied.",
      summary:
        "Inbox-confirmed aggregate listing for multiple senior SAP S/4HANA consultants; individual modules were not stated.",
      skills: ["SAP", "S/4HANA"],
      isConfirmed: true,
      type: "Not stated",
      date: "2026-05",
      historicalState: "Historical May 2026 inbox snapshot; current availability is unverified.",
      isHistorical: true,
      isAggregate: true,
      recordCount: null,
      confirmationScope: "The aggregate inbox listing is confirmed; individual vacancies were not resolved."
    },
    {
      id: "job-2026-05-seek-abap-public-cloud-btp",
      title: "SAP ABAP Developer — Public Cloud & BTP",
      company: "DyFlex Solutions",
      location: "Sydney NSW (Remote, AU/NZ)",
      region: "AU/NZ",
      workMode: "Remote",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "Not stated",
      source: "SEEK",
      provenance: inboxProvenance,
      firstSeen: "2026-05",
      snapshotDate,
      priority: "watch",
      priorityReason:
        "May 2026 inbox record with AU/NZ remote coverage; rate and current availability were not supplied.",
      summary:
        "Inbox-confirmed SAP ABAP developer listing referencing Public Cloud and BTP, with remote AU/NZ coverage.",
      skills: ["ABAP", "SAP Public Cloud", "BTP"],
      isConfirmed: true,
      type: "Not stated",
      date: "2026-05",
      historicalState: "Historical May 2026 inbox snapshot; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The inbox role record is confirmed; its current live status is not."
    },
    {
      id: "job-2026-05-seek-erp-application-specialist",
      title: "ERP Application Specialist (NetSuite/SAP)",
      company: "Life-Space Group",
      location: "Clayton, Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "Other",
      group: "Other ERP",
      module: "Other ERP",
      rate: null,
      engagement: "Not stated",
      source: "SEEK",
      provenance: inboxProvenance,
      firstSeen: "2026-05",
      snapshotDate,
      priority: "watch",
      priorityReason:
        "May 2026 inbox record that broadens coverage beyond SAP; rate and current availability were not supplied.",
      summary:
        "Inbox-confirmed ERP application specialist listing referencing both NetSuite and SAP.",
      skills: ["NetSuite", "SAP", "ERP Applications"],
      isConfirmed: true,
      type: "Not stated",
      date: "2026-05",
      historicalState: "Historical May 2026 inbox snapshot; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The inbox role record is confirmed; its current live status is not."
    },
    {
      id: "job-2026-05-seek-basis-technical-lead",
      title: "SAP Technical Lead (SAP BASIS)",
      company: "Milestone Information Technology",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "Basis",
      rate: null,
      engagement: "Not stated",
      source: "SEEK",
      provenance: inboxProvenance,
      firstSeen: "2026-05",
      snapshotDate,
      priority: "watch",
      priorityReason:
        "May 2026 inbox record for a technical-lead profile; rate and current availability were not supplied.",
      summary: "Inbox-confirmed SAP technical lead listing focused on SAP BASIS.",
      skills: ["SAP BASIS", "Technical Leadership"],
      isConfirmed: true,
      type: "Not stated",
      date: "2026-05",
      historicalState: "Historical May 2026 inbox snapshot; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The inbox role record is confirmed; its current live status is not."
    },
    {
      id: "job-2026-05-seek-sap-specialist",
      title: "SAP Specialist",
      company: "B E Foods Pty Ltd",
      location: "Blacktown, Sydney NSW",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Unclassified",
      module: "Unclassified SAP",
      rate: null,
      engagement: "Not stated",
      source: "SEEK",
      provenance: inboxProvenance,
      firstSeen: "2026-05",
      snapshotDate,
      priority: "watch",
      priorityReason:
        "May 2026 inbox record, but the supplied title does not identify a module, rate or current availability.",
      summary: "Inbox-confirmed SAP specialist listing with no module detail in the supplied notes.",
      skills: ["SAP"],
      isConfirmed: true,
      type: "Not stated",
      date: "2026-05",
      historicalState: "Historical May 2026 inbox snapshot; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The inbox role record is confirmed; its current live status is not."
    },
    {
      id: "job-2025-03-linkedin-fico-adelaide-fifo",
      title: "SAP FICO Functional Consultant — Contract",
      company: "Recruiter InMail",
      location: "Adelaide / FIFO",
      region: "AU",
      workMode: "FIFO",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Contract",
      source: "LinkedIn",
      provenance: inboxProvenance,
      firstSeen: "2025-03",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical March 2025 recruiter outreach; no rate or current availability confirmation was supplied.",
      summary: "Recruiter outreach for a contract SAP FICO functional consultant in Adelaide / FIFO.",
      skills: ["SAP FICO", "FI/CO"],
      isConfirmed: true,
      type: "Contract",
      date: "2025-03",
      historicalState: "Historical recruiter-outreach record; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The recruiter outreach is confirmed; an underlying live posting is not."
    },
    {
      id: "job-2025-03-linkedin-solutions-architect",
      title: "SAP Solutions Architect",
      company: "Recruiter InMail",
      location: "Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Leadership",
      module: "Solution Architect",
      rate: null,
      engagement: "Not stated",
      source: "LinkedIn",
      provenance: inboxProvenance,
      firstSeen: "2025-03",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical March 2025 recruiter outreach; no rate or current availability confirmation was supplied.",
      summary: "Recruiter outreach for an SAP Solutions Architect role in Australia.",
      skills: ["SAP", "Solution Architecture"],
      isConfirmed: true,
      type: "Not stated",
      date: "2025-03",
      historicalState: "Historical recruiter-outreach record; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The recruiter outreach is confirmed; an underlying live posting is not."
    },
    {
      id: "job-2025-01-linkedin-infosys-s4-architect",
      title: "SAP S/4HANA Architect — Perm",
      company: "Infosys",
      location: "Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Leadership",
      module: "Solution Architect",
      rate: null,
      engagement: "Permanent",
      source: "LinkedIn",
      provenance: inboxProvenance,
      firstSeen: "2025-01",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical January 2025 recruiter outreach; no compensation or current availability confirmation was supplied.",
      summary: "Recruiter outreach for a permanent SAP S/4HANA Architect role with Infosys.",
      skills: ["S/4HANA", "SAP Architecture"],
      isConfirmed: true,
      type: "Permanent",
      date: "2025-01",
      historicalState: "Historical recruiter-outreach record; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The recruiter outreach is confirmed; an underlying live posting is not."
    },
    {
      id: "job-2025-01-linkedin-fico-solution-experts",
      title: "SAP FICO Solution Experts — S/4HANA Programme",
      company: "Recruiter InMail",
      location: "Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Not stated",
      source: "LinkedIn",
      provenance: inboxProvenance,
      firstSeen: "2025-01",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical January 2025 recruiter outreach; no rate or current availability confirmation was supplied.",
      summary: "Recruiter outreach for SAP FICO solution experts on an S/4HANA programme.",
      skills: ["SAP FICO", "FI/CO", "S/4HANA"],
      isConfirmed: true,
      type: "Not stated",
      date: "2025-01",
      historicalState: "Historical recruiter-outreach record; current availability is unverified.",
      isHistorical: true,
      isAggregate: true,
      recordCount: null,
      confirmationScope: "The aggregate recruiter outreach is confirmed; individual vacancies were not resolved."
    },
    {
      id: "job-2025-01-linkedin-fico-or-mm",
      title: "SAP FICO or MM Consultant",
      company: "Recruiter InMail",
      location: "Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Not stated",
      source: "LinkedIn",
      provenance: inboxProvenance,
      firstSeen: "2025-01",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical January 2025 recruiter outreach; no rate or current availability confirmation was supplied.",
      summary: "Recruiter outreach seeking an SAP consultant with FICO or MM experience.",
      skills: ["SAP FICO", "FI/CO", "MM"],
      isConfirmed: true,
      type: "Not stated",
      date: "2025-01",
      historicalState: "Historical recruiter-outreach record; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The recruiter outreach is confirmed; an underlying live posting is not."
    },
    {
      id: "job-2024-11-linkedin-abap-fiori",
      title: "SAP ABAP & FIORI — urgent opening",
      company: "Recruiter InMail",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "Not stated",
      source: "LinkedIn",
      provenance: inboxProvenance,
      firstSeen: "2024-11",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "The word “urgent” belongs to a November 2024 recruiter message and must not be treated as a current urgency signal.",
      summary: "Historical recruiter outreach for SAP ABAP and FIORI capability in Melbourne.",
      skills: ["ABAP", "Fiori/UI5"],
      isConfirmed: true,
      type: "Not stated",
      date: "2024-11",
      historicalState: "Historical recruiter-outreach record; the original urgency is stale.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The recruiter outreach is confirmed; an underlying live posting is not."
    },
    {
      id: "job-2024-10-linkedin-fico",
      title: "SAP FICO Consultant",
      company: "Recruiter InMail",
      location: "Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Not stated",
      source: "LinkedIn",
      provenance: inboxProvenance,
      firstSeen: "2024-10",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical October 2024 recruiter outreach; no rate or current availability confirmation was supplied.",
      summary: "Historical recruiter outreach for an SAP FICO Consultant in Australia.",
      skills: ["SAP FICO", "FI/CO"],
      isConfirmed: true,
      type: "Not stated",
      date: "2024-10",
      historicalState: "Historical recruiter-outreach record; current availability is unverified.",
      isHistorical: true,
      isAggregate: false,
      recordCount: 1,
      confirmationScope: "The recruiter outreach is confirmed; an underlying live posting is not."
    },
    {
      id: "job-2024-09-seek-fico-six",
      title: "SAP FICO Consultant (saved-search, 6 jobs)",
      company: "Allura Partners · Paxus · Dept of Health QLD +3",
      location: "All Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Not stated",
      source: "SEEK alert",
      provenance: aggregateProvenance,
      firstSeen: "2024-09",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical September 2024 saved-search alert; the six underlying roles and their current status were not resolved.",
      summary:
        "Historical SEEK saved-search alert grouping six SAP FICO roles across Allura Partners, Paxus, Dept of Health QLD and three other advertisers.",
      skills: ["SAP FICO", "FI/CO"],
      isConfirmed: true,
      type: "Not stated",
      date: "2024-09",
      historicalState: "Historical aggregate alert; current availability is unverified.",
      isHistorical: true,
      isAggregate: true,
      recordCount: 6,
      confirmationScope: "The alert and its stated count are confirmed; individual vacancies were not resolved."
    },
    {
      id: "job-2024-09-seek-nz-fico-two",
      title: "SAP FICO (saved-search, 2 jobs)",
      company: "Capgemini Australia",
      location: "All New Zealand",
      region: "NZ",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Not stated",
      source: "SEEK alert",
      provenance: aggregateProvenance,
      firstSeen: "2024-09",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical September 2024 saved-search alert; the two underlying roles and their current status were not resolved.",
      summary:
        "Historical SEEK saved-search alert for two SAP FICO roles in New Zealand, attributed to Capgemini Australia.",
      skills: ["SAP FICO", "FI/CO"],
      isConfirmed: true,
      type: "Not stated",
      date: "2024-09",
      historicalState: "Historical aggregate alert; current availability is unverified.",
      isHistorical: true,
      isAggregate: true,
      recordCount: 2,
      confirmationScope: "The alert and its stated count are confirmed; individual vacancies were not resolved."
    },
    {
      id: "job-2024-09-seek-mm-twenty",
      title: "SAP Materials Management Consultant (saved-search, 20 jobs)",
      company: "Teletrac Navman · CSL · Capgemini +17",
      location: "All Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "MM",
      rate: null,
      engagement: "Not stated",
      source: "SEEK alert",
      provenance: aggregateProvenance,
      firstSeen: "2024-09",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical September 2024 saved-search alert; the 20 underlying roles and their current status were not resolved.",
      summary:
        "Historical SEEK saved-search alert grouping 20 SAP Materials Management roles across Teletrac Navman, CSL, Capgemini and 17 other advertisers.",
      skills: ["SAP MM", "Materials Management"],
      isConfirmed: true,
      type: "Not stated",
      date: "2024-09",
      historicalState: "Historical aggregate alert; current availability is unverified.",
      isHistorical: true,
      isAggregate: true,
      recordCount: 20,
      confirmationScope: "The alert and its stated count are confirmed; individual vacancies were not resolved."
    },
    {
      id: "job-2024-09-seek-fico-five",
      title: "SAP FICO Consultant (saved-search, 5 jobs)",
      company: "Talent · SAPTURE International · Norco Co-op +2",
      location: "All Australia",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Not stated",
      source: "SEEK alert",
      provenance: aggregateProvenance,
      firstSeen: "2024-09",
      snapshotDate,
      priority: "archive",
      priorityReason:
        "Historical September 2024 saved-search alert; the five underlying roles and their current status were not resolved.",
      summary:
        "Historical SEEK saved-search alert grouping five SAP FICO roles across Talent, SAPTURE International, Norco Co-op and two other advertisers.",
      skills: ["SAP FICO", "FI/CO"],
      isConfirmed: true,
      type: "Not stated",
      date: "2024-09",
      historicalState: "Historical aggregate alert; current availability is unverified.",
      isHistorical: true,
      isAggregate: true,
      recordCount: 5,
      confirmationScope: "The alert and its stated count are confirmed; individual vacancies were not resolved."
    }
  ];

  const prototypePipelineNotice =
    "Prototype example only — this is not a verified project, tender or open role.";

  const pipeline = [
    {
      id: "pipeline-example-public-health-s4",
      name: "Illustrative public-health S/4HANA programme",
      organization: "Example public-sector organisation",
      sector: "Public health",
      location: "Sydney NSW",
      region: "AU",
      signalType: "Example tender signal",
      confidence: "Example only",
      status: "Prototype signal",
      date: null,
      expectedStart: "Illustrative · Q4 2026",
      modules: ["Enterprise Architect", "FI/CO"],
      summary: "Demonstrates how an early transformation signal could be classified before roles appear.",
      evidence: prototypePipelineNotice,
      isPrototype: true
    },
    {
      id: "pipeline-example-nz-integration",
      name: "Illustrative utilities integration uplift",
      organization: "Example New Zealand utility",
      sector: "Utilities",
      location: "Auckland",
      region: "NZ",
      signalType: "Example hiring signal",
      confidence: "Example only",
      status: "Prototype signal",
      date: null,
      expectedStart: "Illustrative · Q1 2027",
      modules: ["BTP", "Integration Suite (CPI/PI-PO)"],
      summary: "Demonstrates a possible BTP and integration capability signal.",
      evidence: prototypePipelineNotice,
      isPrototype: true
    },
    {
      id: "pipeline-example-hr-transformation",
      name: "Illustrative HR transformation",
      organization: "Example transport organisation",
      sector: "Transport",
      location: "Brisbane QLD",
      region: "AU",
      signalType: "Example RFP signal",
      confidence: "Example only",
      status: "Prototype signal",
      date: null,
      expectedStart: "Illustrative · Q4 2026",
      modules: ["HCM/SuccessFactors"],
      summary: "Demonstrates how a future SuccessFactors signal could appear in the pipeline.",
      evidence: prototypePipelineNotice,
      isPrototype: true
    },
    {
      id: "pipeline-example-analytics",
      name: "Illustrative analytics modernisation",
      organization: "Example New Zealand enterprise",
      sector: "Enterprise",
      location: "Wellington",
      region: "NZ",
      signalType: "Example programme signal",
      confidence: "Example only",
      status: "Prototype signal",
      date: null,
      expectedStart: "Illustrative · Q1 2027",
      modules: ["SAC", "BW/4HANA"],
      summary: "Demonstrates an early analytics and data-platform opportunity signal.",
      evidence: prototypePipelineNotice,
      isPrototype: true
    }
  ];

  const inboxOnlyPermission =
    "User-owned alert emails or recruiter messages only; no direct site scraping.";
  const pausedInboxReason =
    "No recurring inbox importer is confirmed running; this source is listed for future permitted alert ingestion.";
  const manualOrLicensedPermission =
    "Manual review, user-owned alerts or a licensed/authorised feed only; scraping permission has not been established.";

  const sources = [
    {
      id: "seek",
      name: "SEEK",
      type: "General job board",
      region: "AU/NZ",
      ingestionMethod: "User-authorized inbox alert parsing",
      permissionBasis: inboxOnlyPermission,
      directScraping: "prohibited",
      status: "prototype",
      statusReason:
        "Historical SEEK alert records are present in this prototype; no recurring importer is confirmed running.",
      health: "historical",
      lastImport: null,
      newCount: null,
      count: 10,
      recordCount: 10,
      isPrototype: true
    },
    {
      id: "linkedin",
      name: "LinkedIn Jobs / InMail",
      type: "General job board / recruiter outreach",
      region: "AU/NZ",
      ingestionMethod: "User-authorized inbox alert and InMail parsing",
      permissionBasis: inboxOnlyPermission,
      directScraping: "prohibited",
      status: "prototype",
      statusReason:
        "Historical LinkedIn recruiter messages are present in this prototype; no recurring importer is confirmed running.",
      health: "historical",
      lastImport: null,
      newCount: null,
      count: 7,
      recordCount: 7,
      isPrototype: true
    },
    {
      id: "indeed-au",
      name: "Indeed Australia",
      type: "General job board",
      region: "AU",
      ingestionMethod: "User-authorized inbox alerts or licensed feed (not configured)",
      permissionBasis: manualOrLicensedPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: pausedInboxReason,
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    {
      id: "indeed-nz",
      name: "Indeed New Zealand",
      type: "General job board",
      region: "NZ",
      ingestionMethod: "User-authorized inbox alerts or licensed feed (not configured)",
      permissionBasis: manualOrLicensedPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: pausedInboxReason,
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    {
      id: "jora",
      name: "Jora",
      type: "General job board",
      region: "AU/NZ",
      ingestionMethod: "User-authorized inbox alerts or licensed feed (not configured)",
      permissionBasis: manualOrLicensedPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: pausedInboxReason,
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    {
      id: "careerone",
      name: "CareerOne",
      type: "General job board",
      region: "AU",
      ingestionMethod: "User-authorized inbox alerts or licensed feed (not configured)",
      permissionBasis: manualOrLicensedPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: pausedInboxReason,
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    {
      id: "adzuna",
      name: "Adzuna",
      type: "Aggregator / API",
      region: "AU/NZ",
      ingestionMethod: "Public aggregator API (not connected)",
      permissionBasis:
        "The supplied notes identify an Adzuna public API; credentials, current terms and implementation still require confirmation.",
      directScraping: "not required",
      status: "paused",
      statusReason: "API connector has not been configured.",
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    {
      id: "trade-me-jobs",
      name: "Trade Me Jobs",
      type: "General job board",
      region: "NZ",
      ingestionMethod: "Manual review or authorised feed (not configured)",
      permissionBasis: manualOrLicensedPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: "No permitted connector or recurring import is configured.",
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    {
      id: "workforce-australia",
      name: "Workforce Australia",
      type: "Government job board",
      region: "AU",
      ingestionMethod: "Manual review or authorised feed (not configured)",
      permissionBasis: manualOrLicensedPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: "No permitted connector or recurring import is configured.",
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    {
      id: "jobs-govt-nz",
      name: "Jobs.govt.nz",
      type: "Government job board",
      region: "NZ",
      ingestionMethod: "Manual review or authorised feed (not configured)",
      permissionBasis: manualOrLicensedPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: "No permitted connector or recurring import is configured.",
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    },
    ...[
      ["peoplebank", "Peoplebank", "AU/NZ"],
      ["paxus", "Paxus", "AU"],
      ["talent-international", "Talent International", "AU/NZ"],
      ["finite-it", "Finite IT Recruitment Solutions", "AU"],
      ["bluefin-resources", "Bluefin Resources", "AU"],
      ["halcyon-knights", "Halcyon Knights", "AU"],
      ["clicks-it", "Clicks IT Recruitment", "AU"],
      ["chandler-macleod", "Chandler Macleod", "AU/NZ"],
      ["hays", "Hays", "AU/NZ"],
      ["randstad-digital", "Randstad Digital", "AU/NZ"],
      ["dfp-recruitment", "DFP Recruitment", "AU"],
      ["u-and-u", "u&u", "AU"],
      ["absolute-it", "Absolute IT", "NZ"],
      ["momentum-consulting", "Momentum Consulting", "NZ"],
      ["robert-walters-nz", "Robert Walters NZ", "NZ"],
      ["madison-recruitment", "Madison Recruitment", "NZ"]
    ].map(([id, name, region]) => ({
      id,
      name,
      type: "Specialist recruiter",
      region,
      ingestionMethod: "User-authorized inbox alerts (not configured)",
      permissionBasis: inboxOnlyPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason: pausedInboxReason,
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    })),
    {
      id: "sapture-international",
      name: "SAPTURE International",
      type: "Specialist recruiter",
      region: "AU/NZ",
      ingestionMethod: "User-authorized inbox alerts (not configured)",
      permissionBasis: inboxOnlyPermission,
      directScraping: "not assessed",
      status: "paused",
      statusReason:
        "Appears in a September 2024 SEEK alert, but independent vendor verification remains an open item in the supplied notes.",
      health: "paused",
      lastImport: null,
      newCount: null,
      count: 0,
      recordCount: 0,
      isPrototype: true
    }
  ];

  const alerts = [
    {
      id: "alert-local-leadership",
      name: "Leadership across AU/NZ",
      query: "stream:SAP group:Leadership region:AU,NZ",
      criteria: "SAP · Leadership · AU/NZ",
      frequency: "On demand",
      channel: "Dashboard only",
      status: "local-only",
      paused: false,
      deliveryEnabled: false,
      storage: "local",
      isPrototype: true
    },
    {
      id: "alert-local-remote",
      name: "Remote SAP roles",
      query: "stream:SAP workMode:Remote",
      criteria: "SAP · Remote",
      frequency: "On demand",
      channel: "Dashboard only",
      status: "local-only",
      paused: false,
      deliveryEnabled: false,
      storage: "local",
      isPrototype: true
    },
    {
      id: "alert-local-fico",
      name: "FI/CO snapshot records",
      query: "stream:SAP module:FI/CO",
      criteria: "SAP · FI/CO",
      frequency: "On demand",
      channel: "Dashboard only",
      status: "local-only",
      paused: false,
      deliveryEnabled: false,
      storage: "local",
      isPrototype: true
    },
    {
      id: "alert-local-pipeline",
      name: "Pipeline examples",
      query: "view:pipeline",
      criteria: "Prototype pipeline signals",
      frequency: "Paused",
      channel: "Dashboard only",
      status: "paused",
      paused: true,
      deliveryEnabled: false,
      storage: "local",
      isPrototype: true
    }
  ];

  window.TalentRadarData = Object.freeze({
    meta: Object.freeze({
      product: "Talent Radar",
      coverage: "AU/NZ",
      snapshotDate,
      snapshotLabel: "May 2026 inbox snapshot",
      dataState: "Static prototype",
      approximateInboxThreadCount: 200,
      approximateInboxThreadCountLabel: "~200",
      confirmedInboxRecordCount: jobs.length,
      sapTaxonomyTagCount: sapGroups.reduce((sum, group) => sum + group.modules.length, 0),
      sourceCount: sources.length,
      lastLiveImport: null,
      priorityRule:
        "Provisional only: stated high day rate and May 2026 snapshot recency. Current availability is not inferred.",
      disclaimer:
        "Inbox confirmation proves the message or alert was received, not that a role is still open. No live scraper, scheduler or external alert delivery is represented."
    }),
    jobs: Object.freeze(jobs),
    pipeline: Object.freeze(pipeline),
    sources: Object.freeze(sources),
    alerts: Object.freeze(alerts),
    modules: Object.freeze(modules),
    sapGroups: Object.freeze(sapGroups),
    otherGroups: Object.freeze(otherGroups)
  });
})();
