(function loadVerifiedTalentRadarJobs() {
  "use strict";

  const verifiedAt = "2026-07-24";
  const provenance =
    "Public job listing opened and its Apply or Quick Apply control confirmed on 24 July 2026.";

  window.TalentRadarLiveJobs = [
    {
      id: "seek-93062441",
      title: "SAP Ariba Consultant",
      company: "IBM",
      location: "Sydney or Melbourne",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "Ariba",
      rate: null,
      engagement: "Full time",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93062441",
      provenance,
      firstSeen: "2026-07-02",
      postedLabel: "Posted 22 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current hybrid SAP Ariba role spanning Sydney and Melbourne.",
      summary: "Ariba sourcing, contracts, supplier lifecycle, buying and invoicing with S/4HANA integration.",
      skills: ["SAP Ariba", "S/4HANA", "Sourcing", "Buying & Invoicing"],
      type: "Full time"
    },
    {
      id: "seek-93275820",
      title: "Functional Consultant – Integration Project (SAP SD)",
      company: "NCSI Australia",
      location: "Macquarie Park, Sydney NSW",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "SD",
      rate: null,
      engagement: "Contract",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93275820",
      provenance,
      firstSeen: "2026-07-13",
      postedLabel: "Posted 11 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current hybrid SAP SD integration contract.",
      summary: "Integration-project role focused on SAP SD and order-to-cash processes.",
      skills: ["SAP SD", "Order to Cash", "Integration", "Functional Consulting"],
      type: "Contract"
    },
    {
      id: "seek-93311670",
      title: "SAP S/4HANA Functional Consultant – Korean Speaking",
      company: "Kia Australia",
      location: "Macquarie Park, Sydney NSW",
      region: "AU",
      workMode: "On-site",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "6-month contract",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93311670",
      provenance,
      firstSeen: "2026-07-14",
      postedLabel: "Posted 10 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current S/4HANA finance contract with possible extension.",
      summary: "S/4HANA functional consulting across FI, CO and finance integrations; Korean language required.",
      skills: ["S/4HANA", "FI/CO", "Fiori", "Finance"],
      type: "Contract"
    },
    {
      id: "seek-93351138",
      title: "SAP S/4HANA Sourcing & Procurement Consultant",
      company: "Speller International",
      location: "Sydney NSW",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "MM",
      rate: null,
      engagement: "Permanent",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93351138",
      provenance,
      firstSeen: "2026-07-16",
      postedLabel: "Posted 8 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Recently posted permanent S/4HANA procurement role.",
      summary: "SAP Public Cloud sourcing and procurement consulting with an immediate start.",
      skills: ["S/4HANA", "Procurement", "SAP Public Cloud", "Sourcing"],
      type: "Full time"
    },
    {
      id: "seek-93072634",
      title: "SAP FICO Consultant",
      company: "COSOL",
      location: "Australia (Remote)",
      region: "AU",
      workMode: "Remote",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: "Flexible day rate",
      engagement: "Contract",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93072634",
      provenance,
      firstSeen: "2026-07-02",
      postedLabel: "Posted 22 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Fully remote anywhere in Australia.",
      summary: "Fully remote FICO delivery role covering S/4HANA, RISE and FI/CO configuration.",
      skills: ["SAP FICO", "S/4HANA", "RISE", "FI/CO"],
      type: "Contract"
    },
    {
      id: "seek-93326560",
      title: "Senior SAP Security Consultant",
      company: "DyFlex Solutions",
      location: "Sydney NSW",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "Security",
      rate: null,
      engagement: "Full time",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93326560",
      provenance,
      firstSeen: "2026-07-15",
      postedLabel: "Posted 9 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Recently posted senior SAP security role.",
      summary: "Senior security consulting across GRC, Fiori, BTP security and S/4HANA.",
      skills: ["SAP Security", "GRC", "BTP", "Fiori"],
      type: "Full time"
    },
    {
      id: "seek-93351412",
      title: "ECP Functional Consultant",
      company: "Speller International",
      location: "Sydney, Melbourne or Brisbane",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "HCM/SuccessFactors",
      rate: null,
      engagement: "Permanent",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93351412",
      provenance,
      firstSeen: "2026-07-16",
      postedLabel: "Posted 8 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current multi-city Employee Central Payroll role.",
      summary: "SuccessFactors Employee Central Payroll consulting with ECC Payroll experience.",
      skills: ["SuccessFactors", "Employee Central Payroll", "ECC Payroll"],
      type: "Full time"
    },
    {
      id: "linkedin-4442014299",
      title: "SAP Developer",
      company: "Talent",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "6-month contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/sap-developer-at-talent-4442014299",
      provenance,
      firstSeen: "2026-07-23",
      postedLabel: "Posted 23 hours ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Newest verified role in the current dataset.",
      summary: "ABAP development across S/4HANA, BTP, RAP, Fiori/UI5 and OData; New Zealand work rights required.",
      skills: ["ABAP", "BTP", "RAP", "Fiori/UI5"],
      type: "Contract"
    },
    {
      id: "linkedin-4327959912",
      title: "SAP S/4HANA ABAP Developer",
      company: "Accenture New Zealand",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "On-site",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "Full time",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/sap-abap-fiori-developer-at-accenture-new-zealand-4327959912",
      provenance,
      firstSeen: "2026-07-17",
      postedLabel: "Posted 1 week ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current S/4HANA engineering role in Auckland.",
      summary: "ABAP OO engineering across S/4HANA, RAP, Fiori Elements, CDS and OData.",
      skills: ["ABAP OO", "S/4HANA", "RAP", "CDS/OData"],
      type: "Full time"
    },
    {
      id: "linkedin-4434434061",
      title: "Senior SAP Developer",
      company: "Absolute IT",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "6-month contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/senior-sap-developer-at-absolute-it-4434434061",
      provenance,
      firstSeen: "2026-07-19",
      postedLabel: "Posted 5 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Recently posted hybrid senior developer contract.",
      summary: "Senior ABAP contract covering S/4HANA, BTP, RAP and Fiori/UI5.",
      skills: ["ABAP", "S/4HANA", "BTP", "Fiori/UI5"],
      type: "Contract"
    },
    {
      id: "linkedin-4410334595",
      title: "SAP ABAP Consultant",
      company: "Hastha Solutions",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "On-site",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "Contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://au.linkedin.com/jobs/view/sap-abap-consultant-contract-melbourne-at-hastha-solutions-4410334595",
      provenance,
      firstSeen: "2026-07-17",
      postedLabel: "Posted 1 week ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current Melbourne ABAP contract.",
      summary: "ABAP consulting role with IS-U and CRM experience.",
      skills: ["ABAP", "IS-U", "CRM"],
      type: "Contract"
    },
    {
      id: "linkedin-4343906251",
      title: "SAP Solution Architect",
      company: "EY",
      location: "Sydney, Melbourne or Canberra",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Leadership",
      module: "Solution Architect",
      rate: null,
      engagement: "Full time",
      source: "LinkedIn Jobs",
      sourceUrl: "https://au.linkedin.com/jobs/view/sap-solution-architect-at-ey-4343906251",
      provenance,
      firstSeen: "2026-07-17",
      postedLabel: "Posted 1 week ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Hybrid leadership opportunity across three Australian cities.",
      summary: "S/4HANA solution architecture for transformation programs using SAP Activate.",
      skills: ["Solution Architecture", "S/4HANA", "SAP Activate"],
      type: "Full time"
    },
    {
      id: "linkedin-4426598728",
      title: "SAP ABAP Developer",
      company: "Tribe Group",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "6-month contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/sap-abap-developer-at-tribe-group-4426598728",
      provenance,
      firstSeen: "2026-07-10",
      postedLabel: "Posted 2 weeks ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current hybrid Auckland SAP development contract.",
      summary: "ABAP and OO development across S/4HANA, RAP, BTP, Fiori/UI5, OData and integrations.",
      skills: ["ABAP/OO", "S/4HANA", "BTP", "RAP"],
      type: "Contract"
    }
  ];
})();
