(function loadVerifiedTalentRadarJobs() {
  "use strict";

  const verifiedAt = "2026-07-24";
  const provenance =
    "Public job listing opened and its Apply or Quick Apply control confirmed on 24 July 2026.";

  window.TalentRadarLiveJobs = [
    {
      id: "seek-93062441",
      title: "SAP Ariba Consultant",
      company: "IBM",
      location: "Sydney or Melbourne",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "Ariba",
      rate: null,
      engagement: "Full time",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93062441",
      provenance,
      firstSeen: "2026-07-02",
      postedLabel: "Posted 22 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current hybrid SAP Ariba role spanning Sydney and Melbourne.",
      summary: "Ariba sourcing, contracts, supplier lifecycle, buying and invoicing with S/4HANA integration.",
      skills: ["SAP Ariba", "S/4HANA", "Sourcing", "Buying & Invoicing"],
      type: "Full time"
    },
    {
      id: "seek-93275820",
      title: "Functional Consultant – Integration Project (SAP SD)",
      company: "NCSI Australia",
      location: "Macquarie Park, Sydney NSW",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "SD",
      rate: null,
      engagement: "Contract",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93275820",
      provenance,
      firstSeen: "2026-07-13",
      postedLabel: "Posted 11 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current hybrid SAP SD integration contract.",
      summary: "Integration-project role focused on SAP SD and order-to-cash processes.",
      skills: ["SAP SD", "Order to Cash", "Integration", "Functional Consulting"],
      type: "Contract"
    },
    {
      id: "seek-93311670",
      title: "SAP S/4HANA Functional Consultant – Korean Speaking",
      company: "Kia Australia",
      location: "Macquarie Park, Sydney NSW",
      region: "AU",
      workMode: "On-site",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "6-month contract",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93311670",
      provenance,
      firstSeen: "2026-07-14",
      postedLabel: "Posted 10 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current S/4HANA finance contract with possible extension.",
      summary: "S/4HANA functional consulting across FI, CO and finance integrations; Korean language required.",
      skills: ["S/4HANA", "FI/CO", "Fiori", "Finance"],
      type: "Contract"
    },
    {
      id: "speller-676212",
      title: "SAP S/4HANA Sourcing & Procurement Consultant",
      company: "Speller International",
      location: "Sydney NSW",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "MM",
      rate: null,
      engagement: "Permanent",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-s-slash-4hana-sourcing-and-procurement-consulting-slash-flexibility-slash-ownership-676212",
      provenance,
      firstSeen: "2026-07-16",
      postedLabel: "Posted 8 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Recently posted permanent S/4HANA procurement role.",
      summary: "SAP Public Cloud sourcing and procurement consulting with an immediate start.",
      skills: ["S/4HANA", "Procurement", "SAP Public Cloud", "Sourcing"],
      type: "Full time"
    },
    {
      id: "seek-93072634",
      title: "SAP FICO Consultant",
      company: "COSOL",
      location: "Australia (Remote)",
      region: "AU",
      workMode: "Remote",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: "Flexible day rate",
      engagement: "Contract",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93072634",
      provenance,
      firstSeen: "2026-07-02",
      postedLabel: "Posted 22 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Fully remote anywhere in Australia.",
      summary: "Fully remote FICO delivery role covering S/4HANA, RISE and FI/CO configuration.",
      skills: ["SAP FICO", "S/4HANA", "RISE", "FI/CO"],
      type: "Contract"
    },
    {
      id: "seek-93326560",
      title: "Senior SAP Security Consultant",
      company: "DyFlex Solutions",
      location: "Sydney NSW",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "Security",
      rate: null,
      engagement: "Full time",
      source: "SEEK",
      sourceUrl: "https://au.seek.com/job/93326560",
      provenance,
      firstSeen: "2026-07-15",
      postedLabel: "Posted 9 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Recently posted senior SAP security role.",
      summary: "Senior security consulting across GRC, Fiori, BTP security and S/4HANA.",
      skills: ["SAP Security", "GRC", "BTP", "Fiori"],
      type: "Full time"
    },
    {
      id: "speller-676221",
      title: "ECP Functional Consultant",
      company: "Speller International",
      location: "Sydney, Melbourne or Brisbane",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "HCM/SuccessFactors",
      rate: null,
      engagement: "Permanent",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/ecp-functional-consultant-676221",
      provenance,
      firstSeen: "2026-07-16",
      postedLabel: "Posted 8 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current multi-city Employee Central Payroll role.",
      summary: "SuccessFactors Employee Central Payroll consulting with ECC Payroll experience.",
      skills: ["SuccessFactors", "Employee Central Payroll", "ECC Payroll"],
      type: "Full time"
    },
    {
      id: "linkedin-4442014299",
      title: "SAP Developer",
      company: "Talent",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "6-month contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/sap-developer-at-talent-4442014299",
      provenance,
      firstSeen: "2026-07-23",
      postedLabel: "Posted 23 hours ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Newest verified role in the current dataset.",
      summary: "ABAP development across S/4HANA, BTP, RAP, Fiori/UI5 and OData; New Zealand work rights required.",
      skills: ["ABAP", "BTP", "RAP", "Fiori/UI5"],
      type: "Contract"
    },
    {
      id: "linkedin-4327959912",
      title: "SAP S/4HANA ABAP Developer",
      company: "Accenture New Zealand",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "On-site",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "Full time",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/sap-abap-fiori-developer-at-accenture-new-zealand-4327959912",
      provenance,
      firstSeen: "2026-07-17",
      postedLabel: "Posted 1 week ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current S/4HANA engineering role in Auckland.",
      summary: "ABAP OO engineering across S/4HANA, RAP, Fiori Elements, CDS and OData.",
      skills: ["ABAP OO", "S/4HANA", "RAP", "CDS/OData"],
      type: "Full time"
    },
    {
      id: "linkedin-4434434061",
      title: "Senior SAP Developer",
      company: "Absolute IT",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "6-month contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/senior-sap-developer-at-absolute-it-4434434061",
      provenance,
      firstSeen: "2026-07-19",
      postedLabel: "Posted 5 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Recently posted hybrid senior developer contract.",
      summary: "Senior ABAP contract covering S/4HANA, BTP, RAP and Fiori/UI5.",
      skills: ["ABAP", "S/4HANA", "BTP", "Fiori/UI5"],
      type: "Contract"
    },
    {
      id: "linkedin-4410334595",
      title: "SAP ABAP Consultant",
      company: "Hastha Solutions",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "On-site",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "Contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://au.linkedin.com/jobs/view/sap-abap-consultant-contract-melbourne-at-hastha-solutions-4410334595",
      provenance,
      firstSeen: "2026-07-17",
      postedLabel: "Posted 1 week ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current Melbourne ABAP contract.",
      summary: "ABAP consulting role with IS-U and CRM experience.",
      skills: ["ABAP", "IS-U", "CRM"],
      type: "Contract"
    },
    {
      id: "linkedin-4343906251",
      title: "SAP Solution Architect",
      company: "EY",
      location: "Sydney, Melbourne or Canberra",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Leadership",
      module: "Solution Architect",
      rate: null,
      engagement: "Full time",
      source: "LinkedIn Jobs",
      sourceUrl: "https://au.linkedin.com/jobs/view/sap-solution-architect-at-ey-4343906251",
      provenance,
      firstSeen: "2026-07-17",
      postedLabel: "Posted 1 week ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Hybrid leadership opportunity across three Australian cities.",
      summary: "S/4HANA solution architecture for transformation programs using SAP Activate.",
      skills: ["Solution Architecture", "S/4HANA", "SAP Activate"],
      type: "Full time"
    },
    {
      id: "linkedin-4426598728",
      title: "SAP ABAP Developer",
      company: "Tribe Group",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "6-month contract",
      source: "LinkedIn Jobs",
      sourceUrl: "https://nz.linkedin.com/jobs/view/sap-abap-developer-at-tribe-group-4426598728",
      provenance,
      firstSeen: "2026-07-10",
      postedLabel: "Posted 2 weeks ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current hybrid Auckland SAP development contract.",
      summary: "ABAP and OO development across S/4HANA, RAP, BTP, Fiori/UI5, OData and integrations.",
      skills: ["ABAP/OO", "S/4HANA", "BTP", "RAP"],
      type: "Contract"
    },
    {
      id: "sap-careers-443281",
      title: "Senior/Principal Retail Consultant",
      company: "SAP",
      location: "Sydney, Melbourne or Brisbane",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "MM",
      rate: null,
      engagement: "Regular full time",
      source: "SAP Careers",
      sourceUrl: "https://jobs.sap.com/job/Southbank-%28Melbourne%29-SeniorPrincipal-Retail-Consultant-VIC-3006/1375390333/",
      provenance,
      firstSeen: "2026-07-13",
      postedLabel: "Posted 13 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Direct employer listing with active Apply control.",
      summary: "Senior SAP Retail consulting role spanning retail, supply-chain processes and SAP Activate delivery.",
      skills: ["SAP Retail", "Supply Chain", "SAP Activate", "Solution Architecture"],
      type: "Full time"
    },
    {
      id: "sap-careers-446519",
      title: "Senior AI Developer – Generative & Agentic AI",
      company: "SAP",
      location: "Sydney, Brisbane, Melbourne or Canberra",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "BTP",
      rate: null,
      engagement: "Regular full time",
      source: "SAP Careers",
      sourceUrl: "https://jobs.sap.com/job/North-Sydney-Senior-AI-Developer-%28Generative-%26-Agentic-AI-%28SAP-BTP%29-NSW-2060/1367716933/",
      provenance,
      firstSeen: "2026-07-21",
      postedLabel: "Posted 21 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Recently posted, multi-city SAP BTP engineering opportunity.",
      summary: "Enterprise GenAI and agentic AI development on SAP BTP, AI Core, HANA and S/4HANA.",
      skills: ["SAP BTP", "AI Core", "S/4HANA", "Generative AI"],
      type: "Full time"
    },
    {
      id: "sap-careers-451719",
      title: "Enterprise Architect – RISE with SAP",
      company: "SAP",
      location: "Melbourne, Sydney or Brisbane",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Leadership",
      module: "Enterprise Architect",
      rate: null,
      engagement: "Regular full time",
      source: "SAP Careers",
      sourceUrl: "https://jobs.sap.com/job/Southbank-%28Melbourne%29-Enterprise-Architect-Rise-Australia-VIC-3006/1392110133/",
      provenance,
      firstSeen: "2026-06-09",
      postedLabel: "Posted 9 Jun 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Direct employer listing remains open with Apply available.",
      summary: "Enterprise architecture role covering RISE with SAP, Clean Core, BTP, LeanIX and Signavio.",
      skills: ["RISE with SAP", "Clean Core", "BTP", "LeanIX"],
      type: "Full time"
    },
    {
      id: "sap-careers-456166",
      title: "Cybersecurity & Compliance Advisor",
      company: "SAP",
      location: "Queensland",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "Security",
      rate: null,
      engagement: "Regular full time",
      source: "SAP Careers",
      sourceUrl: "https://jobs.sap.com/job/Queensland-Cybersecurity-%26-Compliance-Advisor-4000/1411127333/",
      provenance,
      firstSeen: "2026-07-03",
      postedLabel: "Posted 3 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Direct SAP cybersecurity role with active application route.",
      summary: "Customer-facing SAP cloud security, privacy, compliance and AI-risk advisory across ANZ.",
      skills: ["Cybersecurity", "SAP Cloud", "Compliance", "AI Risk"],
      type: "Full time"
    },
    {
      id: "sap-careers-454072",
      title: "Managing Partner – BHP",
      company: "SAP",
      location: "Perth WA",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Leadership",
      module: "Delivery Lead",
      rate: null,
      engagement: "Regular full time",
      source: "SAP Careers",
      sourceUrl: "https://jobs.sap.com/job/Perth-WA-Managing-Partner-BHP-6000/1397646333/",
      provenance,
      firstSeen: "2026-06-25",
      postedLabel: "Posted 25 Jun 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Current direct-employer SAP leadership role in Perth.",
      summary: "Executive account leadership for SAP's strategic BHP relationship and transformation roadmap.",
      skills: ["Account Leadership", "SAP Cloud", "Mining", "Transformation"],
      type: "Full time"
    },
    {
      id: "careerone-accenture-s4-finance",
      title: "SAP S/4HANA Finance Consultant / Lead / Manager",
      company: "Accenture",
      location: "Sydney, Melbourne, Brisbane, Canberra or Perth",
      region: "AU",
      workMode: "On-site",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Permanent full time",
      source: "CareerOne",
      sourceUrl: "https://www.careerone.com.au/jobview/sap-s4hana-finance-consultant-lead-consultant-manager/9004e1ec-8510-11f1-a578-0231708ce3cd",
      provenance,
      firstSeen: "2026-07-21",
      postedLabel: "Posted 21 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Recently posted multi-city S/4HANA Finance role.",
      summary: "Finance transformation positions from consultant through manager across S/4HANA Finance and FI/CO.",
      skills: ["S/4HANA Finance", "FI/CO", "SAP Activate", "Fiori"],
      type: "Full time"
    },
    {
      id: "careerone-paxus-security",
      title: "SAP Security Consultant",
      company: "Paxus",
      location: "Canberra ACT",
      region: "AU",
      workMode: "On-site",
      stream: "SAP",
      group: "Technical",
      module: "Security",
      rate: null,
      engagement: "Permanent full time",
      source: "CareerOne",
      sourceUrl: "https://www.careerone.com.au/jobview/sap-security-consultant/f23eea41-8442-11f1-a578-0231708ce3cd",
      provenance,
      firstSeen: "2026-07-19",
      postedLabel: "Posted 5 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current Canberra security role with active Apply control.",
      summary: "SAP HANA application security and cloud-role design; Australian citizenship and NV1 clearance required.",
      skills: ["SAP Security", "SAP HANA", "Identity Management", "Cloud Roles"],
      type: "Full time"
    },
    {
      id: "jora-capgemini-r2r",
      title: "SAP FICO Record to Report Consultant",
      company: "Capgemini",
      location: "Adelaide SA",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Full time",
      source: "Jora",
      sourceUrl: "https://au.jora.com/job/Consultant-b1a52542614fff0ed8caea8c65d4c1c0",
      provenance,
      firstSeen: "2026-07-10",
      postedLabel: "Posted 14 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current Adelaide hybrid role with company-site application route.",
      summary: "S/4HANA Record-to-Report consulting across GL, AP, AR, asset accounting and financial reporting.",
      skills: ["SAP R2R", "S/4HANA", "FI/CO", "AMS"],
      type: "Full time"
    },
    {
      id: "speller-676589",
      title: "SAP S/4HANA Finance Business Analyst",
      company: "Speller International",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Not stated",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-s-slash-4hana-finance-business-analyst-676589",
      provenance,
      firstSeen: "2026-07-20",
      postedLabel: "Posted 4 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Recently posted on a specialist SAP recruitment site.",
      summary: "Business-facing finance transformation role on a major SAP S/4HANA program.",
      skills: ["S/4HANA", "Finance", "Business Analysis", "Process Design"],
      type: "Not stated"
    },
    {
      id: "speller-676820",
      title: "SAP Project Manager",
      company: "Speller International",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Leadership",
      module: "S/4HANA Program Manager",
      rate: "$1,400–1,550/day",
      engagement: "Contract",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-project-manager-676820",
      provenance,
      firstSeen: "2026-07-22",
      postedLabel: "Posted 2 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "New high-rate ECC6 to S/4HANA RISE transformation role.",
      summary: "Program leadership for an enterprise migration from SAP ECC6 to S/4HANA RISE.",
      skills: ["S/4HANA", "RISE", "ECC6", "Program Delivery"],
      type: "Contract"
    },
    {
      id: "speller-675672",
      title: "SAP SuccessFactors Consultant – Talent",
      company: "Speller International",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "HCM/SuccessFactors",
      rate: null,
      engagement: "Not stated",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-successfactors-consultant-talent-675672",
      provenance,
      firstSeen: "2026-07-09",
      postedLabel: "Posted 15 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current specialist SuccessFactors listing with Apply Now available.",
      summary: "Talent Management consulting across performance, succession, learning and employee experience.",
      skills: ["SuccessFactors", "Talent Management", "Learning", "Employee Experience"],
      type: "Not stated"
    },
    {
      id: "speller-676592",
      title: "SAP S/4HANA Retail & Supply Chain Business Analyst",
      company: "Speller International",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "MM",
      rate: null,
      engagement: "Not stated",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-s-slash-4hana-retail-and-supply-chain-business-analyst-676592",
      provenance,
      firstSeen: "2026-07-20",
      postedLabel: "Posted 4 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Recently posted retail and supply-chain transformation role.",
      summary: "Business analysis for future-state retail and supply-chain processes in a large S/4HANA program.",
      skills: ["S/4HANA", "Retail", "Supply Chain", "Business Analysis"],
      type: "Not stated"
    },
    {
      id: "speller-675757",
      title: "SAP Support Analyst – Supply Chain",
      company: "Speller International",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "MM",
      rate: null,
      engagement: "Permanent",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-support-analyst-supply-chain-675757",
      provenance,
      firstSeen: "2026-07-10",
      postedLabel: "Posted 14 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current permanent SAP supply-chain support opportunity.",
      summary: "Functional support and continuous improvement for SAP supply-chain solutions in manufacturing.",
      skills: ["SAP Supply Chain", "Functional Support", "Manufacturing", "Continuous Improvement"],
      type: "Full time"
    },
    {
      id: "speller-675555",
      title: "SAP Solution Architect – SuccessFactors ECP",
      company: "Speller International",
      location: "Melbourne VIC with interstate travel",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Leadership",
      module: "Solution Architect",
      rate: "Circa $1,500/day",
      engagement: "Contract",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-solution-architect-successfactors-ecp-675555",
      provenance,
      firstSeen: "2026-07-08",
      postedLabel: "Posted 16 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "High-rate payroll transformation architecture opportunity.",
      summary: "Solution architecture leadership for a major SuccessFactors Employee Central Payroll transformation.",
      skills: ["SuccessFactors", "ECP", "Payroll", "Solution Architecture"],
      type: "Contract"
    },
    {
      id: "speller-675554",
      title: "SAP Project Coordinator – WMS Rollout",
      company: "Speller International",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Leadership",
      module: "Delivery Lead",
      rate: "$600–700/day",
      engagement: "Contract",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-project-coordinator-wms-rollout-675554",
      provenance,
      firstSeen: "2026-07-08",
      postedLabel: "Posted 16 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current multi-site SAP and WMS deployment role.",
      summary: "Project coordination for a multi-site SAP, warehouse and operational-technology rollout.",
      skills: ["SAP", "WMS", "Deployment", "Project Coordination"],
      type: "Contract"
    },
    {
      id: "speller-677006",
      title: "Senior SAP Procurement Functional Consultant",
      company: "Speller International",
      location: "Brisbane QLD",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "MM",
      rate: null,
      engagement: "Not stated",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/senior-sap-procurement-functional-consultant-s-slash-4hana-677006",
      provenance,
      firstSeen: "2026-07-24",
      postedLabel: "Posted about 7 hours ago",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Newest verified Speller listing in the audit.",
      summary: "Procurement functional delivery within a large-scale SAP S/4HANA transformation.",
      skills: ["S/4HANA", "Procurement", "MM", "Functional Design"],
      type: "Not stated"
    },
    {
      id: "speller-675200",
      title: "SAP Systems Accountant",
      company: "Speller International",
      location: "Adelaide SA",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "FI/CO",
      rate: null,
      engagement: "Permanent",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-systems-accountant-leading-south-australian-organisation-675200",
      provenance,
      firstSeen: "2026-07-06",
      postedLabel: "Posted 18 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Verified hybrid SAP finance opportunity in Adelaide.",
      summary: "Finance systems role supporting SAP processes and ongoing digital transformation.",
      skills: ["SAP Finance", "Systems Accounting", "Process Improvement", "Reporting"],
      type: "Full time"
    },
    {
      id: "speller-675659",
      title: "SAP Integration Consultant – PI/PO/CPI/BTP",
      company: "Speller International",
      location: "Adelaide SA",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Technical",
      module: "Integration Suite (CPI/PI-PO)",
      rate: null,
      engagement: "Permanent",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/sap-integration-consultant-pi-slash-po-slash-cpi-slash-btp-integration-suite-675659",
      provenance,
      firstSeen: "2026-07-09",
      postedLabel: "Posted 15 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Current Adelaide specialist integration opportunity.",
      summary: "Permanent SAP integration role covering PI/PO, CPI and SAP BTP Integration Suite.",
      skills: ["SAP PI/PO", "CPI", "BTP", "Integration Suite"],
      type: "Full time"
    },
    {
      id: "speller-675193",
      title: "Change Analyst – SAP ECC Implementation",
      company: "Speller International",
      location: "Auckland, New Zealand",
      region: "NZ",
      workMode: "Not stated",
      stream: "SAP",
      group: "Leadership",
      module: "Delivery Lead",
      rate: null,
      engagement: "Not stated",
      source: "Speller International",
      sourceUrl: "https://www.spellerinternational.com.au/job/change-analyst-675193",
      provenance,
      firstSeen: "2026-07-06",
      postedLabel: "Posted 18 days ago",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Verified live SAP ECC change role in New Zealand.",
      summary: "Change analysis and adoption support for a large-scale SAP ECC rollout in Auckland.",
      skills: ["SAP ECC", "Change Management", "Training", "Stakeholder Engagement"],
      type: "Not stated"
    },
    {
      id: "exclaim-18639",
      title: "Integration Architect – SAP S/4HANA",
      company: "Exclaim IT",
      location: "Brisbane QLD",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Leadership",
      module: "Solution Architect",
      rate: null,
      engagement: "Contract",
      source: "Exclaim IT",
      sourceUrl: "https://exclaim-it.com.au/jobs/integration-architect-18639/",
      provenance,
      firstSeen: "2026-07-03",
      postedLabel: "Posted 3 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Hybrid architecture role on a major public-sector S/4HANA program.",
      summary: "Integration architecture across S/4HANA, BTP, CPI, Cloud ALM and connected enterprise platforms.",
      skills: ["S/4HANA", "BTP", "CPI", "Integration Architecture"],
      type: "Contract"
    },
    {
      id: "exclaim-18544",
      title: "Principal SAP Developer",
      company: "Exclaim IT",
      location: "Brisbane QLD",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "12-month contract",
      source: "Exclaim IT",
      sourceUrl: "https://exclaim-it.com.au/jobs/principal-developer-18544/",
      provenance,
      firstSeen: "2026-05-13",
      postedLabel: "Posted 13 May 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Direct application form remains available on the recruiter page.",
      summary: "Principal development role across ABAP, RAP, Fiori, CDS, OData and SAP BTP.",
      skills: ["ABAP", "RAP", "Fiori", "BTP"],
      type: "Contract"
    },
    {
      id: "peoplebank-270210",
      title: "SAP Senior Developer",
      company: "Peoplebank",
      location: "Adelaide, Canberra, Melbourne or Queensland",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: null,
      engagement: "Up to 12 months with extensions",
      source: "Peoplebank",
      sourceUrl: "https://www.peoplebank.com.au/job-details/sap-senior-developer-in-sap-erp-crm-jobs-1487290",
      provenance,
      firstSeen: "2026-04-02",
      postedLabel: "Published 2 Apr 2026 · Apply Now still active",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Older 2026 listing retained only because its direct Apply Now control is still active.",
      summary: "Government SAP development contract covering S/4HANA, ABAP, BRF+, UI5, Fiori and CRM.",
      skills: ["S/4HANA", "ABAP", "UI5", "Fiori"],
      type: "Contract"
    },
    {
      id: "deloitte-41507",
      title: "SAP EAM Functional Senior Consultant",
      company: "Deloitte",
      location: "Melbourne VIC",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Functional",
      module: "PM",
      rate: null,
      engagement: "Full time",
      source: "Deloitte Careers",
      sourceUrl: "https://jobs.deloitte.com.au/job/Melbourne-SAP-EAM-Functional-Senior-Consultant-VIC/1363963266/",
      provenance,
      firstSeen: "2026-07-08",
      postedLabel: "Posted 8 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Direct employer Apply Now route confirmed.",
      summary: "Senior functional consulting across SAP Plant Maintenance and Enterprise Asset Management.",
      skills: ["SAP EAM", "SAP PM", "S/4HANA", "Asset Management"],
      type: "Full time"
    },
    {
      id: "indeed-capgemini-consultants",
      title: "SAP Consultants – Australia (10 positions)",
      company: "Capgemini",
      location: "Sydney, Melbourne, Brisbane, Canberra or another major Australian city",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Other",
      module: "General PM/BA",
      rate: null,
      engagement: "Contract / fixed term",
      source: "Indeed",
      sourceUrl: "https://au.indeed.com/viewjob?jk=cf65702d7fc36ebc",
      provenance,
      firstSeen: "2026-07-24",
      postedLabel: "Listing date not stated · checked 24 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Multi-hire national opportunity with a current company-site application route.",
      summary: "Ten consulting positions for certified SAP functional or development practitioners across Australia.",
      skills: ["SAP Consulting", "Functional", "Development", "S/4HANA"],
      type: "Contract"
    },
    {
      id: "michael-page-7062621",
      title: "SAP ABAP Developer – ICT",
      company: "Michael Page",
      location: "Brisbane QLD",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Technical",
      module: "ABAP/OO-ABAP",
      rate: "$125–142/hour",
      engagement: "Long-term temporary contract",
      source: "Michael Page",
      sourceUrl: "https://www.michaelpage.com.au/job-detail/sap-abap-developer-ict/ref/jn-072026-7062621",
      provenance,
      firstSeen: "2026-07-24",
      postedLabel: "Listing date not stated · checked 24 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Current hybrid Brisbane role with a direct Apply control.",
      summary: "S/4HANA and BTP development using ABAP, RAP, Fiori/UI5, CDS and OData.",
      skills: ["ABAP", "RAP", "BTP", "Fiori/UI5"],
      type: "Contract"
    },
    {
      id: "michael-page-7058645",
      title: "Senior SAP Project Manager",
      company: "Michael Page",
      location: "West Perth WA",
      region: "AU",
      workMode: "Not stated",
      stream: "SAP",
      group: "Leadership",
      module: "S/4HANA Program Manager",
      rate: "Competitive daily rate",
      engagement: "Temporary contract",
      source: "Michael Page",
      sourceUrl: "https://www.michaelpage.com.au/job-detail/senior-project-manager/ref/jn-072026-7058645",
      provenance,
      firstSeen: "2026-07-24",
      postedLabel: "Listing date not stated · checked 24 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "priority",
      priorityReason: "Current Perth SAP transformation role with direct Apply.",
      summary: "Lead the SAP RFP, vendor selection and procurement phase for a major enterprise transformation.",
      skills: ["SAP Transformation", "RFP", "Vendor Selection", "Program Governance"],
      type: "Contract"
    },
    {
      id: "michael-page-6953601",
      title: "Business Analyst – SAP SuccessFactors",
      company: "Michael Page",
      location: "Moorabbin, Melbourne VIC",
      region: "AU",
      workMode: "Hybrid",
      stream: "SAP",
      group: "Functional",
      module: "HCM/SuccessFactors",
      rate: null,
      engagement: "15–18 month fixed-term contract",
      source: "Michael Page",
      sourceUrl: "https://www.michaelpage.com.au/job-detail/business-analyst-sap-successfactors/ref/jn-022026-6953601",
      provenance,
      firstSeen: "2026-07-24",
      postedLabel: "Listing date not stated · Apply active 24 Jul 2026",
      verifiedAt,
      applyStatus: "open",
      priority: "current",
      priorityReason: "Retained because it remains in the live SAP search and the direct Apply control is active.",
      summary: "SuccessFactors business analysis focused on data migration, process mapping and solution documentation.",
      skills: ["SuccessFactors", "Data Migration", "Business Analysis", "Process Mapping"],
      type: "Fixed term"
    }
  ];
})();
